<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>$(DefineConstants);OPENTK</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <None Remove=".gitignore" />
    <None Remove="Resources\Config\generalConfig.xml" />
    <None Remove="Resources\Shaders\PosShader.frag" />
    <None Remove="Resources\Shaders\PosShader.vert" />
    <None Remove="Resources\Shaders\TextureShader.frag" />
    <None Remove="Resources\Shaders\TextureShader.vert" />
    <None Remove="Resources\Textures\wall.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="opentk" Version="4.8.2" />
    <PackageReference Include="SharpDX" Version="4.2.0" />
    <PackageReference Include="stbimagesharp" Version="2.27.13" />
  </ItemGroup>

  <ItemGroup>
    <None Update="Resources\Fonts\latin_sas_math_16pt.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Fonts\latin_sas_math_16pt_0.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Shaders\FontShader_default.frag">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="Resources\Shaders\FontShader_default.vert">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\**">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
